[output]
deny = ["warnings"]
quiet = false

[advisories]
ignore = [
	"RUSTSEC-2021-0145", # atty: potential unaligned read
	"RUSTSEC-2021-0127", # serde_cbor is unmaintained
	"RUSTSEC-2021-0139", # ansi_term is Unmaintained
	"RUSTSEC-2024-0370", # proc-macro-error is unmaintained
]
